In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [82]:
df = pd.read_csv("Data.csv")
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [83]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [84]:
from sklearn.impute import SimpleImputer

In [85]:
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

In [86]:
X[:, 1:] = imputer.fit_transform(X[:, 1:])

In [87]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, LabelEncoder

In [88]:
trans = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

In [89]:
X = trans.fit_transform(X)

In [90]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [91]:
y = LabelEncoder().fit_transform(y)

In [92]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [93]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [104]:
from sklearn.model_selection import train_test_split

In [105]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [106]:
x_train

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0]], dtype=object)

In [107]:
from sklearn.preprocessing import StandardScaler

In [100]:
sc = StandardScaler()

In [109]:
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])

In [110]:
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [111]:
x_train

array([[0.0, 0.0, 1.0, 0.20224268907094922, -0.9767851812443],
       [0.0, 1.0, 0.0, 0.39157627032885883, 0.2065202954630813],
       [1.0, 0.0, 0.0, 1.011213445354745, 1.0326014773154035],
       [1.0, 0.0, 0.0, 1.6308506203806314, 1.7358868078113],
       [0.0, 1.0, 0.0, -1.1575166672358568, -0.7758465153883297],
       [1.0, 0.0, 0.0, -0.07315161094055589, 0.5302548126754777],
       [1.0, 0.0, 0.0, -0.38297019845349906, -0.373969183676389],
       [0.0, 0.0, 1.0, -1.6222445485052717, -1.3786625129562409]],
      dtype=object)

In [112]:
x_test

array([[0.0, 1.0, 0.0, 1.9406692078935746, 2.1377641395232407],
       [0.0, 0.0, 1.0, 0.08175768281591567, -0.07256118489243342]],
      dtype=object)

In [113]:
y_train

array([0, 1, 0, 1, 0, 1, 1, 1])