In [104]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [105]:
iris = load_iris()

# X contains 4 features
X = iris.data

# Type iris
y = iris.target

# split
np.random.seed(7)

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=20, test_size=130)

In [106]:
def custom_weights(distances):
    return np.exp(-distances ** 2 / 4)

In [102]:
def predict(n, p):
    knn = KNeighborsClassifier(n_neighbors=n, p=p, weights=custom_weights)
    knn.fit(X_train, y_train)
    
    y_pred = knn.predict(X_test)
    
    return accuracy_score(y_test, y_pred)

In [103]:
print(predict(5, 2))

[[0.98019867 0.97287468 0.90032452 0.89583414 0.87371591]
 [0.95839047 0.87153435 0.8478937  0.8478937  0.83110428]
 [0.99252805 0.96560542 0.95599748 0.93941306 0.91621887]
 [0.97775124 0.8824969  0.87371591 0.87371591 0.87153435]
 [0.82489432 0.80051501 0.73161563 0.71892373 0.68728928]
 [0.81261324 0.81058425 0.73528287 0.67705687 0.63444797]
 [0.91393119 0.89136614 0.83527021 0.83110428 0.78270454]
 [0.97775124 0.97530991 0.97287468 0.96560542 0.83110428]
 [0.97775124 0.96560542 0.95122942 0.95122942 0.93472772]
 [0.97530991 0.90937293 0.85641518 0.8478937  0.84155829]
 [0.95599748 0.90937293 0.89136614 0.89136614 0.87371591]
 [0.91164921 0.87371591 0.86718755 0.81668648 0.78270454]
 [0.96560542 0.91621887 0.90710234 0.80856032 0.79851622]
 [0.85001609 0.75767556 0.62188506 0.60049558 0.41686202]
 [0.99501248 0.95361047 0.95122942 0.94176453 0.91164921]
 [0.97775124 0.91393119 0.8847059  0.87371591 0.82902912]
 [0.91393119 0.76720595 0.76720595 0.71355197 0.70999312]
 [0.98511194 0

In [60]:
m = 0

for i in range(1, 20):
    for j in range(1, 50):
        m = max(m, predict(i, j))
    
print(m)

0.9615384615384616
