In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [32]:
a = np.random.rand(5, 3) * 10

In [33]:
a

array([[7.89082388, 4.19435862, 0.53392602],
       [2.55330026, 6.83984497, 6.44164747],
       [3.0215191 , 4.45209936, 9.5479337 ],
       [9.0856996 , 8.08393966, 0.26969235],
       [3.21360123, 8.4079525 , 3.47909494]])

In [34]:
a = np.sum(a * a, 1)
print(a)

[ 80.14282275  94.79764355 120.11380447 147.97275154  93.12499967]


In [35]:
z = np.arange(1, 6, 1)

In [36]:
z

array([1, 2, 3, 4, 5])

In [37]:
a.dot(z)

1687.5955277610105

In [39]:
a

array([ 80.14282275,  94.79764355, 120.11380447, 147.97275154,
        93.12499967])

In [40]:
z

array([1, 2, 3, 4, 5])

In [43]:
print(np.sum(z))
a + np.sum(z)

15


array([ 95.14282275, 109.79764355, 135.11380447, 162.97275154,
       108.12499967])

In [ ]:
[] * []